/** Daftar bank yang tersedia untuk penarikan dana di Indonesia. */
export const INDONESIAN_BANKS = [
  'BCA (Bank Central Asia)',
  'Mandiri (Bank Mandiri)',
  'BRI (Bank Rakyat Indonesia)',
  'BNI (Bank Negara Indonesia)',
  'BSI (Bank Syariah Indonesia)',
  'BTN (Bank Tabungan Negara)',
  'CIMB Niaga',
  'Danamon',
  'Permata Bank',
  'OCBC NISP',
  'Maybank',
  'Bukopin',
  'Panin Bank',
  'BNC (Bank Neo Commerce)',
  'Jago',
  'Sea Bank',
  'Bank Mega',
  'Bank Sinarmas',
  'Bank BTPN',
  'Bank Mayapada',
  'Bank Maspion',
  'Bank Woori Saudara',
  'BJB (Bank Jabar Banten)',
  'Bank Aceh',
  'Bank Sumut (Bank Sumatera Utara)',
  'Bank Sumbar (Bank Sumatera Barat)',
  'Bank Sumsel Babel',
  'Bank Riau Kepri',
  'Bank Kalsel',
  'Bank Kaltimtara',
  'Bank Kalteng',
  'Bank Sulselbar',
  'Bank Sultra',
  'Bank SulutGo',
  'Bank Sulteng',
  'Bank NTB Syariah',
  'Bank NTT',
  'Bank Papua',
  'Bank Maluku',
  'Bank Lampung',
  'Bank Jambi',
  'Bank Bengkulu',
] as const

export type BankName = (typeof INDONESIAN_BANKS)[number]
